### ISSUE TITLE
Sample Data, Parameters

### ISSUE THREAD

**Issue by ankur6ue** [inejc/paragraph-vectors#20]
Thanks for making this available. Would you happen to have some sample data and good initial value of the parameters to test this with?

**Comment by inejc** [comment]
I can provide the data and pre-trained model from the [Example of trained vectors](https://github.com/inejc/paragraph-vectors#example-of-trained-vectors) section from README if that's still useful to you.

**Comment by landmann** [comment]
How long did it take you to train this and what were the parameters you used?

**Comment by inejc** [comment]
Unfortunately, I can't comment on that since I lost the models and the training logs.

**Comment by landmann** [comment]
Gotcha. Any ball-park estimates, though? Hours, days, weeks?

**Comment by inejc** [comment]
2-4 days I would say. But it really depends on the dataset size (number of documents + their lengths), hyperparameters and the hardware. What are your numbers/hardware?
