### ISSUE TITLE
How to get the vectors for each document?

### ISSUE THREAD

**Issue by monajalal** [inejc/paragraph-vectors#26]
I did all the steps you mentioned but I felt the step that would show how to create the vector for a given document was missing. 

Basically, I am interested in outputing example_vectors.txt/.csv that in each line has a vector for each document in example.csv.

How should I do that? Can you please add it to your tutorial?

**Comment by inejc** [comment]
Hi, the procedure is described in the `Export trained paragraph vectors to a csv file` section of the readme.

**Comment by luciferkonn** [comment]
Hi, I'm still quite confused about how to see the document embedding...
